### PR TITLE
Added newer ghc versions to .travis.yml file

### PR DESCRIPTION
**Pull request by sethryder**
Addresses #28.

Lets see if they work!

### CODE REVIEW

**Comment by sethryder** [comment]
Looks like 8.4.4 and 8.6.1 failed.

If I am looking at the logs properly, seems they failed on building the "HGL-3.2.3.1" package.

**Comment by chriz-zeller** [comment]
@sethryder thanks for checking and adding. Could you please put the two failing versions in a comment in the travis file and reference Issue #30 . This would be the last step of issue #28 .

**Comment by sethryder** [comment]
@chriz-keera Sure.

Does this look OK? https://github.com/sethryder/Haskelloids/commit/480087f53aa3bc2c637979c714d14e28f125253f

(Wasn't sure if it should be inline or just commented at the top of the file below the first 3 lines of comments)

**Comment by chriz-zeller** [comment]
Yes, thats perfect. Thanks for the PR @sethryder .

**Pull request merged**
